name: MMO-RPG
version: '${project.version}'
main: at.feddis08.mmorpg.MMORPG
api-version: 1.19
load: POSTWORLD
authors: [ Feddis08 ]
commands:
  Test:
  gm:
  startUp:
  reset:
  install:
  tpworld:
  loadWorld:
  rank:
  mail:
  setScoreboard:
  setInventoryTrack:
  setPortalTrack:
  setWarp:
  warp:
  removeWarp:
  discord: