name: MMO-RPG
version: '${project.version}'
main: at.feddis08.mmorpg.MMORPG
api-version: 1.18
load: STARTUP
authors: [ Feddis08 ]
commands:
  Test:
  gm:
  startUp:
  reset:
  install:
  tpworld:
  loadWorld:
  rank:
  mail:
